# Generated by Django 2.1.3 on 2018-11-24 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('info', models.CharField(max_length=200, verbose_name='info')),
            ],
            options={
                'verbose_name': 'Contact info',
                'verbose_name_plural': 'Contact info',
            },
        ),
        migrations.CreateModel(
            name='ContactInfoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Contact info type',
                'verbose_name_plural': 'Contact info types',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('abstract', models.TextField(verbose_name='abstract')),
                ('selected', models.BooleanField(default=False, verbose_name='is_selected')),
                ('date', models.DateField(null=True, verbose_name='date')),
                ('start_time', models.TimeField(null=True, verbose_name='start')),
                ('end_time', models.TimeField(null=True, verbose_name='end')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agenda',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_keynote', models.BooleanField(default=False, verbose_name='is keynote')),
                ('bio', models.TextField(verbose_name='short bio')),
                ('picture', models.ImageField(null=True, upload_to='', verbose_name='picture')),
                ('sessions', models.ManyToManyField(related_name='speakers', to='agenda.Presentation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Track'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='info_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.ContactInfoType'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='agenda.Speaker'),
        ),
    ]
