# Generated by Django 2.0.4 on 2018-04-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('info', models.CharField(max_length=200, verbose_name='info')),
            ],
            options={
                'verbose_name': 'Contact info',
                'verbose_name_plural': 'Contact info',
            },
        ),
        migrations.CreateModel(
            name='ContactInfoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Contact info type',
                'verbose_name_plural': 'Contact info types',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('abstract', models.TextField(verbose_name='abstract')),
                ('date', models.DateField(verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start')),
                ('end_time', models.TimeField(verbose_name='end')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agenda',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('is_keynote', models.BooleanField(default=False, verbose_name='is keynote')),
                ('bio', models.TextField(verbose_name='short bio')),
                ('picture', models.ImageField(upload_to='', verbose_name='picture')),
                ('sessions', models.ManyToManyField(related_name='speakers', to='agenda.Presentation')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Track'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='info_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.ContactInfoType'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='agenda.Speaker'),
        ),
    ]
