# Generated by Django 2.1.3 on 2018-11-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='is_selected'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='date',
            field=models.DateField(null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Track'),
        ),
    ]
